name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Submodule
        run: git clone -b main https://github.com/clashperk/clashofclans.js.git lib

      - name: Copy CHANGELOG.md
        run: cp lib/CHANGELOG.md docs/changelog.md

      - name: Copy README.md
        run: |
          rm -rf docs/intro.md
          echo "---" >> docs/intro.md
          echo "sidebar_position: 1" >> docs/intro.md
          echo "title: 'Welcome'" >> docs/intro.md
          echo "sidebar_label: 'Welcome'" >> docs/intro.md
          echo "slug: /" >> docs/intro.md
          echo "---" >> docs/intro.md
          cat lib/README.md >> docs/intro.md

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          working-directory: ./build
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}